# Generated by Django 5.2.3 on 2025-06-21 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="client's name or company name", max_length=200)),
                ('email', models.EmailField(help_text="client's email address", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text="client's phone number", max_length=15)),
                ('company', models.CharField(blank=True, help_text="client's company name if diff from name", max_length=200)),
                ('company_size', models.CharField(choices=[('startup', 'Startup (1-10 employees)'), ('small', 'Small (11-50 employees)'), ('medium', 'Medium (51-200 employees)'), ('large', 'Large (201+ employees)')], default='startup', help_text="size of client's company", max_length=20)),
                ('industry', models.CharField(blank=True, help_text="industry of client's company", max_length=200)),
                ('website', models.URLField(blank=True, help_text="client's company website")),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, default='Faisalabad', help_text="client's city", max_length=200)),
                ('state', models.CharField(blank=True, default='Punjab', help_text="client's state or province", max_length=200)),
                ('zip_code', models.CharField(blank=True, default='38000', help_text="client's postal code", max_length=20)),
                ('country', models.CharField(blank=True, default='Pakistan', help_text="client's country", max_length=200)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text="client's annual revenue in PKR", max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this client currently active?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client')),
                ('priority_level', models.IntegerField(default=3, help_text='Priority level of the client (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('account_manager', models.ForeignKey(blank=True, help_text='User who manages this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['company'], name='clients_cli_company_deac7e_idx'), models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx')],
            },
        ),
    ]
