# Generated by Django 5.2.3 on 2025-06-26 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='Name of the school', max_length=200, unique=True)),
                ('address', models.CharField(blank=True, help_text='Address of the school', max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the school', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address of the school', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website of the school')),
                ('school_type', models.CharField(choices=[('primary', 'Primary'), ('intermediate', 'College'), ('university', 'University')], default='primary', help_text='Type of the school', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the school was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the school was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Name of the subject', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the subject')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subject was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the subject was last updated')),
                ('school', models.ForeignKey(help_text='School offering the subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schoolManagement.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(help_text='Name of the teacher', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the teacher was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the teacher was last updated')),
                ('school', models.ForeignKey(help_text='School where the teacher works', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schoolManagement.school')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects taught by the teacher', related_name='teachers', to='schoolManagement.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the student', max_length=200)),
                ('age', models.PositiveIntegerField(help_text='Age of the student', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(help_text='Grade or class of the student', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the student was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the student was last updated')),
                ('school', models.ForeignKey(help_text='School the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolManagement.school')),
                ('teachers', models.ManyToManyField(blank=True, help_text='Teachers assigned to the student', related_name='students', to='schoolManagement.teacher')),
            ],
        ),
    ]
